apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    run: rng
  name: rng
spec:
  selector:
    matchLabels:
      run: rng
  template:
    metadata:
      labels:
        run: rng
    spec:
      containers:
      - image: dockercoins/rng:v0.1
        name: rng
